version: '2'
services:
  db:
    build: db
    restart: always
    # env_file: db/.env
    ports:
      - "5432:5432"
    volumes: 
      - datavolume:/var/lib/postgresql/data 
     
  django:
    build: djangoserver
    restart: always
    env_file: djangoserver/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes: 
      - ./djangoserver/quecolectivo:/code/quecolectivo
    command: bash wait-for-postgres.sh db gunicorn -w 8 --reload --pythonpath '/code/quecolectivo/' quecolectivo.wsgi -b 0.0.0.0:8000
volumes:
  datavolume: