services:
  db:
    extends: docker-compose-common.yml
    # Publish the port so it's visible on the host, you can access the db directly
    expose:
    # Expose port 5432 so it's only visibile on the container, not the host
      - "5432"
    volumes: 
      - datavolume:/var/lib/postgresql/data 
     
  django:
    extends: docker-compose-common.yml
    environment:
    # Environment variables to configure pgsql on startup.
    # Environment variables with only a key are resolved to their values on
    # the machine Compose is running on. We do this to prevent ourselves
    # from committing sensitive data to GitHub.
      - DJANGO_SETTINGS_MODULE=quecolectivo.settings
      - POSTGRES_DATABASE=laplata
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - PGPASSWORD
    expose:
    # Expose port 8000 so it's only visibile on the container, not the host
      - "8000"
    depends_on:
      - db
    links:
      - db
    volumes:
    # Mount the app dir in the container so our changes to the app code
    # are also changed in the container
      - ./djangoserver/quecolectivo:/code/quecolectivo
    command: bash wait-for-postgres.sh db gunicorn -w 8 --reload --pythonpath '/code/quecolectivo/' quecolectivo.wsgi -b 0.0.0.0:8000
    # Run Gunicorn to serve app requests and reload on change so we can see our
    # changes to the app code

  nginx:
    extends: docker-compose-common.yml
    ports:
      - 80:80
    links:
      - django

volumes:
  datavolume: