 version: '2'
 services:
   db:
     build: db
     environment: 
       -  POSTGRES_USER=postgres
       -  POSTGRES_PASSWORD=fedefede
     ports:
       - "5432:5432"
     
   server:
     build: .
     environment:
       -  PGPASSWORD=fedefede
     ports:
       - "8000:8000"
     depends_on:
       - db
     links:
       - db
     command: bash wait-for-postgres.sh db python manage.py runserver 0.0.0.0:8000